# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.
services:
  postgres:
    image: postgres:12.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=intern
      - POSTGRES_PASSWORD=1gjAVnJ
      - POSTGRES_DB=card_db
      - POSTGRES_SCHEMA=custom
    expose:
      - 5432
    network_mode: host
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    name: host
    external: true
