#
# application.yml — main Spring Boot configuration file.

app:
  pagination-limit: 20
  security:
    data-keystore:
      location: "${DATA_KEYSTORE_PATH:file:./docker/data-secret.p12}"
      key-alias: "data-encrypt-key"
      password: ${KEYSTORE_PASSWORD:1gjAVnJ}
      type: PKCS12
    jwt-keystore:
      location: "${JWT_KEYSTORE_PATH:file:./docker/jwt-secret.p12}"
      key-alias: "jwt-sign-key"
      password: ${KEYSTORE_PASSWORD:1gjAVnJ}
      type: PKCS12
    tokenExpiration: 15
    refreshTokenExpiration: 30

server:
  port: ${APP_PORT:8081}

spring:

  application:
    name: Bank Cards
  profiles:
    active: production
  main:
    web-application-type: servlet

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  datasource:
    url: ${POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/card_db}
    username: ${POSTGRES_USER:intern}
    password: ${POSTGRES_PASSWORD:1gjAVnJ}
    hikari:
      schema: custom
      driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jakarta:
          persistence:
            schema-generation:
              create-database-schemas: true
        format_sql: true
        default_schema: custom
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    default-schema: custom
    liquibase-schema: public
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/card_db}
    user: intern
    password: 1gjAVnJ
    contexts: production, test
    parameters:
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      schemaName: custom
      tokenLifetime: ${app.security.tokenExpiration}
      refreshTokenLifetime: ${app.security.refreshTokenExpiration}
    drop-first: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.apache.catalina: OFF
    org.hibernate: OFF
    org.springframework: ERROR
    liquibase: OFF

springdoc:
  api-docs:
    enabled: true
    path: /openapi-docs
  swagger-ui:
    enabled: true
    path: /index.html
  enable-spring-security: true
